-- แยกข้อมูล auth ของ admin ไปตาราง admin_auth
-- admins = ข้อมูลโปรไฟล์, admin_auth = password_hash และข้อมูลล็อกอิน

BEGIN;

-- ---------------------------------------------------------------------------
-- admin_auth
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_auth (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id       BIGINT       NOT NULL REFERENCES admins (id),
  password_hash  TEXT         NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admin_auth IS 'ข้อมูล auth ของ admin เช่น password hash';
COMMENT ON COLUMN admin_auth.id IS 'PK';
COMMENT ON COLUMN admin_auth.admin_id IS 'FK → admins.id (1 admin ต่อ 1 auth ที่ active)';
COMMENT ON COLUMN admin_auth.password_hash IS 'รหัสผ่านที่ hash แล้ว';
COMMENT ON COLUMN admin_auth.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_auth.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_auth.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_auth_admin_id_active_uidx
  ON admin_auth (admin_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_auth_set_updated_at ON admin_auth;
CREATE TRIGGER admin_auth_set_updated_at
  BEFORE UPDATE ON admin_auth
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ย้าย password_hash จาก admins → admin_auth (เฉพาะแถวที่ยังไม่มี auth)
INSERT INTO admin_auth (admin_id, password_hash, created_at, updated_at)
SELECT a.id, a.password_hash, a.created_at, a.updated_at
FROM admins a
WHERE a.password_hash IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM admin_auth aa
    WHERE aa.admin_id = a.id
      AND aa.deleted_at IS NULL
  );

-- ลบคอลัมน์ password_hash ออกจาก admins
ALTER TABLE admins DROP COLUMN IF EXISTS password_hash;

COMMIT;
