BEGIN;

-- last_login_at on admins (อัปเดตตอน login สำเร็จ)
ALTER TABLE admins
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;

COMMENT ON COLUMN admins.last_login_at IS
  'เวลา login ล่าสุด — อัปเดตตอน login สำเร็จ';

-- admin_log: ประวัติการใช้งานของ admin
CREATE TABLE IF NOT EXISTS admin_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id     BIGINT       NOT NULL REFERENCES admins (id),
  action       VARCHAR(64)  NOT NULL,
  entity_type  VARCHAR(64),
  entity_id    BIGINT,
  message      TEXT,
  meta         JSONB,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_log IS
  'ประวัติการใช้งานของ admin — โดยปกติ insert อย่างเดียว';
COMMENT ON COLUMN admin_log.id IS 'PK';
COMMENT ON COLUMN admin_log.admin_id IS 'FK → admins.id ผู้ทำรายการ';
COMMENT ON COLUMN admin_log.action IS
  'ชนิดเหตุการณ์ เช่น login, create, update, soft_delete';
COMMENT ON COLUMN admin_log.entity_type IS
  'ชนิดข้อมูลที่เกี่ยวกับ action เช่น order, user, list_price, admin';
COMMENT ON COLUMN admin_log.entity_id IS 'id ของข้อมูลที่เกี่ยวข้อง (nullable)';
COMMENT ON COLUMN admin_log.message IS 'ข้อความเพิ่มเติม';
COMMENT ON COLUMN admin_log.meta IS 'รายละเอียดเพิ่มเติมแบบ JSON (optional)';
COMMENT ON COLUMN admin_log.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_log.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_log.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS admin_log_admin_id_idx
  ON admin_log (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_action_idx
  ON admin_log (action)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_entity_idx
  ON admin_log (entity_type, entity_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_created_at_idx
  ON admin_log (created_at DESC)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_log_set_updated_at ON admin_log;
CREATE TRIGGER admin_log_set_updated_at
  BEFORE UPDATE ON admin_log
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
