BEGIN;

-- ---------------------------------------------------------------------------
-- admin_menu_label
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_label (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_label IS
  'กลุ่ม label ของเมนูฝั่ง admin เช่น การจัดการข้อมูล, รายงาน';
COMMENT ON COLUMN admin_menu_label.id IS 'PK';
COMMENT ON COLUMN admin_menu_label.code IS
  'รหัส label สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_label.name IS 'ชื่อที่แสดงบนเมนู';
COMMENT ON COLUMN admin_menu_label.is_active IS 'สถานะเปิดใช้งาน label';
COMMENT ON COLUMN admin_menu_label.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_menu_label.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_label.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_label.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_label_code_active_uidx
  ON admin_menu_label (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_label_set_updated_at ON admin_menu_label;
CREATE TRIGGER admin_menu_label_set_updated_at
  BEFORE UPDATE ON admin_menu_label
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_menu_tab
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_label_id BIGINT       NOT NULL REFERENCES admin_menu_label (id),
  code          VARCHAR(64)  NOT NULL,
  name          VARCHAR(255) NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order    INTEGER      NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab IS
  'tab เมนูที่อยู่ภายใต้ label แต่ละกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab.menu_label_id IS 'FK → admin_menu_label.id';
COMMENT ON COLUMN admin_menu_tab.code IS
  'รหัส tab สำหรับอ้างอิงสิทธิ์ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_tab.name IS 'ชื่อ tab ที่แสดงบน UI';
COMMENT ON COLUMN admin_menu_tab.is_active IS 'สถานะเปิดใช้งาน tab';
COMMENT ON COLUMN admin_menu_tab.sort_order IS 'ลำดับการแสดงผลในกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_code_active_uidx
  ON admin_menu_tab (code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_label_id_idx
  ON admin_menu_tab (menu_label_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_set_updated_at ON admin_menu_tab;
CREATE TRIGGER admin_menu_tab_set_updated_at
  BEFORE UPDATE ON admin_menu_tab
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_permission_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permission_action (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  description  TEXT,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permission_action IS
  'master ของ action สิทธิ์ เช่น view/add/edit/delete/export';
COMMENT ON COLUMN admin_permission_action.id IS 'PK';
COMMENT ON COLUMN admin_permission_action.code IS
  'รหัส action สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_permission_action.name IS 'ชื่อ action ที่แสดง';
COMMENT ON COLUMN admin_permission_action.is_active IS 'สถานะเปิดใช้งาน action';
COMMENT ON COLUMN admin_permission_action.description IS 'รายละเอียดเพิ่มเติม';
COMMENT ON COLUMN admin_permission_action.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_permission_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permission_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permission_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permission_action_code_active_uidx
  ON admin_permission_action (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permission_action_set_updated_at ON admin_permission_action;
CREATE TRIGGER admin_permission_action_set_updated_at
  BEFORE UPDATE ON admin_permission_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_permission_action (code, name, description, sort_order)
SELECT seed.code, seed.name, seed.description, seed.sort_order
FROM (
  VALUES
    ('view', 'View', 'ดูข้อมูล', 1),
    ('add', 'Add', 'เพิ่มข้อมูล', 2),
    ('edit', 'Edit', 'แก้ไขข้อมูล', 3),
    ('delete', 'Delete', 'ลบข้อมูล', 4),
    ('export', 'Export', 'ส่งออกข้อมูล', 5)
) AS seed(code, name, description, sort_order)
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_permission_action apa
  WHERE apa.code = seed.code
    AND apa.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_menu_tab_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab_action (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_tab_id           BIGINT       NOT NULL REFERENCES admin_menu_tab (id),
  permission_action_id  BIGINT       NOT NULL REFERENCES admin_permission_action (id),
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at            TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab_action IS
  'mapping ว่า tab ใดรองรับ action ใดได้บ้าง';
COMMENT ON COLUMN admin_menu_tab_action.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab_action.menu_tab_id IS
  'FK → admin_menu_tab.id';
COMMENT ON COLUMN admin_menu_tab_action.permission_action_id IS
  'FK → admin_permission_action.id';
COMMENT ON COLUMN admin_menu_tab_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_action_pair_active_uidx
  ON admin_menu_tab_action (menu_tab_id, permission_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_tab_id_idx
  ON admin_menu_tab_action (menu_tab_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_action_id_idx
  ON admin_menu_tab_action (permission_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_action_set_updated_at ON admin_menu_tab_action;
CREATE TRIGGER admin_menu_tab_action_set_updated_at
  BEFORE UPDATE ON admin_menu_tab_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_permissions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permissions (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id            BIGINT       NOT NULL REFERENCES admins (id),
  menu_tab_action_id  BIGINT       NOT NULL REFERENCES admin_menu_tab_action (id),
  is_allowed          BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at          TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permissions IS
  'สิทธิ์ราย admin ว่าอนุญาต action ใดใน tab ไหน';
COMMENT ON COLUMN admin_permissions.id IS 'PK';
COMMENT ON COLUMN admin_permissions.admin_id IS 'FK → admins.id';
COMMENT ON COLUMN admin_permissions.menu_tab_action_id IS
  'FK → admin_menu_tab_action.id';
COMMENT ON COLUMN admin_permissions.is_allowed IS
  'true = อนุญาต, false = ปฏิเสธ';
COMMENT ON COLUMN admin_permissions.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permissions.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permissions.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permissions_admin_action_active_uidx
  ON admin_permissions (admin_id, menu_tab_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_admin_id_idx
  ON admin_permissions (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_menu_tab_action_id_idx
  ON admin_permissions (menu_tab_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permissions_set_updated_at ON admin_permissions;
CREATE TRIGGER admin_permissions_set_updated_at
  BEFORE UPDATE ON admin_permissions
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
