-- Bann Laundry schema
-- Soft delete: deleted_at IS NULL = แถวยังใช้
-- Query ปกติทุกตาราง: WHERE deleted_at IS NULL
-- Unique ของเบอร์ / อีเมล / ticket / code ใช้ partial index

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
  'อัปเดต updated_at อัตโนมัติทุกครั้งที่ UPDATE';

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone       VARCHAR(32)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  note        TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  users IS 'ลูกค้า';
COMMENT ON COLUMN users.id IS 'PK';
COMMENT ON COLUMN users.phone IS 'เบอร์โทร — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN users.name IS 'ชื่อลูกค้า';
COMMENT ON COLUMN users.note IS 'หมายเหตุ';
COMMENT ON COLUMN users.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN users.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN users.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS users_phone_active_uidx
  ON users (phone)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admins
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          VARCHAR(255) NOT NULL,
  display_name   VARCHAR(255) NOT NULL,
  role           VARCHAR(32)  NOT NULL DEFAULT 'staff'
                   CHECK (role IN ('owner', 'admin', 'staff')),
  last_login_at  TIMESTAMPTZ,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admins IS 'พนักงาน / ผู้ดูแลระบบ (ข้อมูลโปรไฟล์)';
COMMENT ON COLUMN admins.id IS 'PK';
COMMENT ON COLUMN admins.email IS 'อีเมล — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN admins.display_name IS 'ชื่อที่แสดง';
COMMENT ON COLUMN admins.role IS 'owner | admin | staff';
COMMENT ON COLUMN admins.last_login_at IS 'เวลา login ล่าสุด — อัปเดตตอน login สำเร็จ';
COMMENT ON COLUMN admins.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admins.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admins.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admins_email_active_uidx
  ON admins (email)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admins_set_updated_at ON admins;
CREATE TRIGGER admins_set_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_auth
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_auth (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id       BIGINT       NOT NULL REFERENCES admins (id),
  password_hash  TEXT         NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admin_auth IS 'ข้อมูล auth ของ admin เช่น password hash';
COMMENT ON COLUMN admin_auth.id IS 'PK';
COMMENT ON COLUMN admin_auth.admin_id IS 'FK → admins.id (1 admin ต่อ 1 auth ที่ active)';
COMMENT ON COLUMN admin_auth.password_hash IS 'รหัสผ่านที่ hash แล้ว';
COMMENT ON COLUMN admin_auth.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_auth.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_auth.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_auth_admin_id_active_uidx
  ON admin_auth (admin_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_auth_set_updated_at ON admin_auth;
CREATE TRIGGER admin_auth_set_updated_at
  BEFORE UPDATE ON admin_auth
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- service_type
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_type (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(64)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  service_type IS 'ประเภทบริการ เช่น ซัก อบ พับ';
COMMENT ON COLUMN service_type.id IS 'PK';
COMMENT ON COLUMN service_type.code IS 'รหัสบริการ — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN service_type.name IS 'ชื่อบริการ';
COMMENT ON COLUMN service_type.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN service_type.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN service_type.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS service_type_code_active_uidx
  ON service_type (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS service_type_set_updated_at ON service_type;
CREATE TRIGGER service_type_set_updated_at
  BEFORE UPDATE ON service_type
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO service_type (code, name)
SELECT seed.code, seed.name
FROM (
  VALUES
    ('wash', 'ซัก'),
    ('wash_iron', 'ซักรีด')
) AS seed(code, name)
WHERE NOT EXISTS (
  SELECT 1
  FROM service_type st
  WHERE st.code = seed.code
    AND st.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- list_type
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS list_type (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(64)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  size        VARCHAR(64)  NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  list_type IS 'ชนิดรายการผ้า คู่ name + size เช่น เสื้อผ้า/normal, เสื้อผ้า/large';
COMMENT ON COLUMN list_type.id IS 'PK';
COMMENT ON COLUMN list_type.code IS 'รหัสสำหรับ logic เช่น clothes_normal — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN list_type.name IS 'ชื่อแสดง เช่น เสื้อผ้า ผ้านวม ชุดชั้นใน ชุดสูท';
COMMENT ON COLUMN list_type.size IS 'ขนาด เช่น normal, large';
COMMENT ON COLUMN list_type.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN list_type.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN list_type.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS list_type_code_active_uidx
  ON list_type (code)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS list_type_name_size_active_uidx
  ON list_type (name, size)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS list_type_set_updated_at ON list_type;
CREATE TRIGGER list_type_set_updated_at
  BEFORE UPDATE ON list_type
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO list_type (code, name, size)
SELECT seed.code, seed.name, seed.size
FROM (
  VALUES
    ('clothes_normal', 'เสื้อผ้า', 'normal'),
    ('clothes_large', 'เสื้อผ้า', 'large'),
    ('duvet_normal', 'ผ้านวม', 'normal'),
    ('duvet_large', 'ผ้านวม', 'large'),
    ('underwear_normal', 'ชุดชั้นใน', 'normal'),
    ('suit_normal', 'ชุดสูท', 'normal'),
    ('suit_large', 'ชุดสูท', 'large')
) AS seed(code, name, size)
WHERE NOT EXISTS (
  SELECT 1
  FROM list_type lt
  WHERE lt.code = seed.code
    AND lt.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- list_price
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS list_price (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_type_id  BIGINT         NOT NULL REFERENCES service_type (id),
  list_type_id     BIGINT         NOT NULL REFERENCES list_type (id),
  unit_price       NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ
);

COMMENT ON TABLE  list_price IS 'ราคาต่อหน่วย ตามบริการ × ชนิดผ้า';
COMMENT ON COLUMN list_price.id IS 'PK';
COMMENT ON COLUMN list_price.service_type_id IS 'FK → service_type.id';
COMMENT ON COLUMN list_price.list_type_id IS 'FK → list_type.id';
COMMENT ON COLUMN list_price.unit_price IS 'ราคาต่อหน่วย';
COMMENT ON COLUMN list_price.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN list_price.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN list_price.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS list_price_service_list_active_uidx
  ON list_price (service_type_id, list_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS list_price_service_type_id_idx
  ON list_price (service_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS list_price_list_type_id_idx
  ON list_price (list_type_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS list_price_set_updated_at ON list_price;
CREATE TRIGGER list_price_set_updated_at
  BEFORE UPDATE ON list_price
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO list_price (service_type_id, list_type_id, unit_price)
SELECT st.id, lt.id, seed.unit_price
FROM (
  VALUES
    ('clothes_normal', 'wash', 7.00),
    ('clothes_normal', 'wash_iron', 15.00),
    ('clothes_large', 'wash', 10.00),
    ('clothes_large', 'wash_iron', 20.00),
    ('duvet_normal', 'wash', 100.00),
    ('duvet_normal', 'wash_iron', 200.00),
    ('duvet_large', 'wash', 150.00),
    ('duvet_large', 'wash_iron', 250.00),
    ('underwear_normal', 'wash', 5.00),
    ('underwear_normal', 'wash_iron', 10.00),
    ('suit_normal', 'wash', 25.00),
    ('suit_normal', 'wash_iron', 50.00),
    ('suit_large', 'wash', 35.00),
    ('suit_large', 'wash_iron', 70.00)
) AS seed(list_type_code, service_type_code, unit_price)
JOIN list_type lt
  ON lt.code = seed.list_type_code
 AND lt.deleted_at IS NULL
JOIN service_type st
  ON st.code = seed.service_type_code
 AND st.deleted_at IS NULL
WHERE NOT EXISTS (
  SELECT 1
  FROM list_price lp
  WHERE lp.service_type_id = st.id
    AND lp.list_type_id = lt.id
    AND lp.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_no   VARCHAR(64)    NOT NULL,
  user_id     BIGINT         NOT NULL REFERENCES users (id),
  admin_id    BIGINT         REFERENCES admins (id),
  status          VARCHAR(32)    NOT NULL DEFAULT 'received'
                    CHECK (status IN (
                      'received',
                      'processing',
                      'ready',
                      'completed',
                      'cancelled'
                    )),
  payment_status  VARCHAR(32)    NOT NULL DEFAULT 'unpaid'
                    CHECK (payment_status IN ('unpaid', 'paid')),
  subtotal        NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  discount        NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total           NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  note            TEXT,
  created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ,
  CHECK (total = subtotal - discount)
);

COMMENT ON TABLE  orders IS 'ออเดอร์ซักรีด';
COMMENT ON COLUMN orders.id IS 'PK';
COMMENT ON COLUMN orders.ticket_no IS 'เลขใบรับผ้า — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN orders.user_id IS 'FK → users.id ลูกค้า';
COMMENT ON COLUMN orders.admin_id IS 'FK → admins.id พนักงานที่รับออเดอร์';
COMMENT ON COLUMN orders.status IS 'สถานะงาน: received | processing | ready | completed | cancelled';
COMMENT ON COLUMN orders.payment_status IS 'สถานะชำระเงิน: unpaid = ยังไม่จ่าย, paid = จ่ายแล้ว';
COMMENT ON COLUMN orders.subtotal IS 'ยอดก่อนส่วนลด';
COMMENT ON COLUMN orders.discount IS 'ส่วนลด';
COMMENT ON COLUMN orders.total IS 'ยอดสุทธิ = subtotal - discount';
COMMENT ON COLUMN orders.note IS 'หมายเหตุออเดอร์';
COMMENT ON COLUMN orders.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN orders.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN orders.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS orders_ticket_no_active_uidx
  ON orders (ticket_no)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_user_id_idx
  ON orders (user_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_admin_id_idx
  ON orders (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_status_idx
  ON orders (status)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_payment_status_idx
  ON orders (payment_status)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS orders_set_updated_at ON orders;
CREATE TRIGGER orders_set_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         BIGINT         NOT NULL REFERENCES orders (id),
  service_type_id  BIGINT         NOT NULL REFERENCES service_type (id),
  list_type_id     BIGINT         NOT NULL REFERENCES list_type (id),
  list_price_id    BIGINT         REFERENCES list_price (id),
  qty              INTEGER        NOT NULL CHECK (qty > 0),
  unit_price       NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  line_total       NUMERIC(12, 2) NOT NULL CHECK (line_total >= 0),
  note             TEXT,
  created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ,
  CHECK (line_total = qty * unit_price)
);

COMMENT ON TABLE  order_items IS 'รายการในออเดอร์';
COMMENT ON COLUMN order_items.id IS 'PK';
COMMENT ON COLUMN order_items.order_id IS 'FK → orders.id';
COMMENT ON COLUMN order_items.service_type_id IS 'FK → service_type.id snapshot ประเภทบริการ';
COMMENT ON COLUMN order_items.list_type_id IS 'FK → list_type.id snapshot ชนิดผ้า';
COMMENT ON COLUMN order_items.list_price_id IS 'FK → list_price.id ราคาที่อ้างอิงตอนสร้าง (nullable ถ้าราคาถูกลบ)';
COMMENT ON COLUMN order_items.qty IS 'จำนวน';
COMMENT ON COLUMN order_items.unit_price IS 'ราคาต่อหน่วย ณ ตอนสร้างรายการ';
COMMENT ON COLUMN order_items.line_total IS 'qty * unit_price';
COMMENT ON COLUMN order_items.note IS 'หมายเหตุรายการ';
COMMENT ON COLUMN order_items.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN order_items.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN order_items.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS order_items_order_id_idx
  ON order_items (order_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS order_items_service_type_id_idx
  ON order_items (service_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS order_items_list_type_id_idx
  ON order_items (list_type_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS order_items_set_updated_at ON order_items;
CREATE TRIGGER order_items_set_updated_at
  BEFORE UPDATE ON order_items
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- order_log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     BIGINT      NOT NULL REFERENCES orders (id),
  admin_id     BIGINT      REFERENCES admins (id),
  from_status  VARCHAR(32),
  to_status    VARCHAR(32),
  action       VARCHAR(64) NOT NULL,
  message      TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  order_log IS 'ประวัติออเดอร์ โดยปกติ insert อย่างเดียว';
COMMENT ON COLUMN order_log.id IS 'PK';
COMMENT ON COLUMN order_log.order_id IS 'FK → orders.id';
COMMENT ON COLUMN order_log.admin_id IS 'FK → admins.id ผู้ทำรายการ';
COMMENT ON COLUMN order_log.from_status IS 'สถานะเดิม (NULL ได้ เช่นตอนสร้างออเดอร์)';
COMMENT ON COLUMN order_log.to_status IS 'สถานะใหม่';
COMMENT ON COLUMN order_log.action IS 'ชนิดเหตุการณ์ เช่น create, status_change, note';
COMMENT ON COLUMN order_log.message IS 'ข้อความเพิ่มเติม';
COMMENT ON COLUMN order_log.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN order_log.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN order_log.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS order_log_order_id_idx
  ON order_log (order_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS order_log_admin_id_idx
  ON order_log (admin_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS order_log_set_updated_at ON order_log;
CREATE TRIGGER order_log_set_updated_at
  BEFORE UPDATE ON order_log
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id     BIGINT       NOT NULL REFERENCES admins (id),
  action       VARCHAR(64)  NOT NULL,
  entity_type  VARCHAR(64),
  entity_id    BIGINT,
  message      TEXT,
  meta         JSONB,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_log IS 'ประวัติการใช้งานของ admin — โดยปกติ insert อย่างเดียว';
COMMENT ON COLUMN admin_log.id IS 'PK';
COMMENT ON COLUMN admin_log.admin_id IS 'FK → admins.id ผู้ทำรายการ';
COMMENT ON COLUMN admin_log.action IS 'ชนิดเหตุการณ์ เช่น login, create, update, soft_delete';
COMMENT ON COLUMN admin_log.entity_type IS 'ชนิดข้อมูลที่เกี่ยวกับ action เช่น order, user, list_price, admin';
COMMENT ON COLUMN admin_log.entity_id IS 'id ของข้อมูลที่เกี่ยวข้อง (nullable)';
COMMENT ON COLUMN admin_log.message IS 'ข้อความเพิ่มเติม';
COMMENT ON COLUMN admin_log.meta IS 'รายละเอียดเพิ่มเติมแบบ JSON (optional)';
COMMENT ON COLUMN admin_log.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_log.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_log.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS admin_log_admin_id_idx
  ON admin_log (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_action_idx
  ON admin_log (action)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_entity_idx
  ON admin_log (entity_type, entity_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_created_at_idx
  ON admin_log (created_at DESC)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_log_set_updated_at ON admin_log;
CREATE TRIGGER admin_log_set_updated_at
  BEFORE UPDATE ON admin_log
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_menu_label
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_label (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_label IS 'กลุ่ม label ของเมนูฝั่ง admin เช่น การจัดการข้อมูล, รายงาน';
COMMENT ON COLUMN admin_menu_label.id IS 'PK';
COMMENT ON COLUMN admin_menu_label.code IS 'รหัส label สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_label.name IS 'ชื่อที่แสดงบนเมนู';
COMMENT ON COLUMN admin_menu_label.is_active IS 'สถานะเปิดใช้งาน label';
COMMENT ON COLUMN admin_menu_label.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_menu_label.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_label.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_label.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_label_code_active_uidx
  ON admin_menu_label (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_label_set_updated_at ON admin_menu_label;
CREATE TRIGGER admin_menu_label_set_updated_at
  BEFORE UPDATE ON admin_menu_label
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_label (code, name, is_active, sort_order)
SELECT seed.code, seed.name, TRUE, seed.sort_order
FROM (
  VALUES
    ('dashboard', 'แดชบอร์ด', 1),
    ('management', 'การจัดการ', 2),
    ('activity-history', 'ประวัติการใช้งาน', 3)
) AS seed(code, name, sort_order)
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_label aml
  WHERE aml.code = seed.code
    AND aml.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_menu_tab
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_label_id BIGINT       NOT NULL REFERENCES admin_menu_label (id),
  code          VARCHAR(64)  NOT NULL,
  name          VARCHAR(255) NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order    INTEGER      NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab IS 'tab เมนูที่อยู่ภายใต้ label แต่ละกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab.menu_label_id IS 'FK → admin_menu_label.id';
COMMENT ON COLUMN admin_menu_tab.code IS 'รหัส tab สำหรับอ้างอิงสิทธิ์ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_tab.name IS 'ชื่อ tab ที่แสดงบน UI';
COMMENT ON COLUMN admin_menu_tab.is_active IS 'สถานะเปิดใช้งาน tab';
COMMENT ON COLUMN admin_menu_tab.sort_order IS 'ลำดับการแสดงผลในกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_code_active_uidx
  ON admin_menu_tab (code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_label_id_idx
  ON admin_menu_tab (menu_label_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_set_updated_at ON admin_menu_tab;
CREATE TRIGGER admin_menu_tab_set_updated_at
  BEFORE UPDATE ON admin_menu_tab
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_tab (menu_label_id, code, name, is_active, sort_order)
SELECT lbl.id, seed.code, seed.name, TRUE, seed.sort_order
FROM (
  VALUES
    ('dashboard', 'overview', 'ภาพรวม', 1),
    ('dashboard', 'bi', 'วิเคราะห์ BI', 2),
    ('management', 'orders', 'ออเดอร์', 0),
    ('management', 'customers', 'ลูกค้า', 1),
    ('management', 'service-types', 'ประเภทบริการ', 2),
    ('management', 'list-prices', 'ราคาบริการ', 3),
    ('management', 'admins', 'ผู้ดูแลระบบ', 4),
    ('activity-history', 'order_log', 'ประวัติออเดอร์', 1),
    ('activity-history', 'admin_log', 'ประวัติแอดมิน', 2)
) AS seed(label_code, code, name, sort_order)
INNER JOIN admin_menu_label lbl
  ON lbl.code = seed.label_code
 AND lbl.deleted_at IS NULL
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_tab amt
  WHERE amt.code = seed.code
    AND amt.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_permission_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permission_action (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  description  TEXT,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permission_action IS 'master ของ action สิทธิ์ เช่น view/add/edit/delete/export';
COMMENT ON COLUMN admin_permission_action.id IS 'PK';
COMMENT ON COLUMN admin_permission_action.code IS 'รหัส action สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_permission_action.name IS 'ชื่อ action ที่แสดง';
COMMENT ON COLUMN admin_permission_action.is_active IS 'สถานะเปิดใช้งาน action';
COMMENT ON COLUMN admin_permission_action.description IS 'รายละเอียดเพิ่มเติม';
COMMENT ON COLUMN admin_permission_action.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_permission_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permission_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permission_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permission_action_code_active_uidx
  ON admin_permission_action (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permission_action_set_updated_at ON admin_permission_action;
CREATE TRIGGER admin_permission_action_set_updated_at
  BEFORE UPDATE ON admin_permission_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_permission_action (code, name, description, sort_order)
SELECT seed.code, seed.name, seed.description, seed.sort_order
FROM (
  VALUES
    ('view', 'View', 'ดูข้อมูล', 1),
    ('add', 'Add', 'เพิ่มข้อมูล', 2),
    ('edit', 'Edit', 'แก้ไขข้อมูล', 3),
    ('delete', 'Delete', 'ลบข้อมูล', 4),
    ('export', 'Export', 'ส่งออกข้อมูล', 5)
) AS seed(code, name, description, sort_order)
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_permission_action apa
  WHERE apa.code = seed.code
    AND apa.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_menu_tab_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab_action (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_tab_id           BIGINT       NOT NULL REFERENCES admin_menu_tab (id),
  permission_action_id  BIGINT       NOT NULL REFERENCES admin_permission_action (id),
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at            TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab_action IS 'mapping ว่า tab ใดรองรับ action ใดได้บ้าง';
COMMENT ON COLUMN admin_menu_tab_action.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab_action.menu_tab_id IS 'FK → admin_menu_tab.id';
COMMENT ON COLUMN admin_menu_tab_action.permission_action_id IS 'FK → admin_permission_action.id';
COMMENT ON COLUMN admin_menu_tab_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_action_pair_active_uidx
  ON admin_menu_tab_action (menu_tab_id, permission_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_tab_id_idx
  ON admin_menu_tab_action (menu_tab_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_action_id_idx
  ON admin_menu_tab_action (permission_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_action_set_updated_at ON admin_menu_tab_action;
CREATE TRIGGER admin_menu_tab_action_set_updated_at
  BEFORE UPDATE ON admin_menu_tab_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_tab_action (menu_tab_id, permission_action_id)
SELECT mt.id, pa.id
FROM (
  VALUES
    ('overview', 'view'),
    ('bi', 'view'),
    ('orders', 'view'),
    ('orders', 'add'),
    ('orders', 'edit'),
    ('orders', 'delete'),
    ('orders', 'export'),
    ('customers', 'view'),
    ('customers', 'add'),
    ('customers', 'edit'),
    ('customers', 'delete'),
    ('customers', 'export'),
    ('service-types', 'view'),
    ('service-types', 'add'),
    ('service-types', 'edit'),
    ('service-types', 'delete'),
    ('service-types', 'export'),
    ('list-prices', 'view'),
    ('list-prices', 'add'),
    ('list-prices', 'edit'),
    ('list-prices', 'delete'),
    ('list-prices', 'export'),
    ('admins', 'view'),
    ('admins', 'add'),
    ('admins', 'edit'),
    ('admins', 'delete'),
    ('admins', 'export'),
    ('order_log', 'view'),
    ('order_log', 'add'),
    ('admin_log', 'view')
) AS seed(tab_code, action_code)
INNER JOIN admin_menu_tab mt
  ON mt.code = seed.tab_code
 AND mt.deleted_at IS NULL
INNER JOIN admin_permission_action pa
  ON pa.code = seed.action_code
 AND pa.deleted_at IS NULL
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_tab_action mta
  WHERE mta.menu_tab_id = mt.id
    AND mta.permission_action_id = pa.id
    AND mta.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_permissions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permissions (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id            BIGINT       NOT NULL REFERENCES admins (id),
  menu_tab_action_id  BIGINT       NOT NULL REFERENCES admin_menu_tab_action (id),
  is_allowed          BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at          TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permissions IS 'สิทธิ์ราย admin ว่าอนุญาต action ใดใน tab ไหน';
COMMENT ON COLUMN admin_permissions.id IS 'PK';
COMMENT ON COLUMN admin_permissions.admin_id IS 'FK → admins.id';
COMMENT ON COLUMN admin_permissions.menu_tab_action_id IS 'FK → admin_menu_tab_action.id';
COMMENT ON COLUMN admin_permissions.is_allowed IS 'true = อนุญาต, false = ปฏิเสธ';
COMMENT ON COLUMN admin_permissions.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permissions.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permissions.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permissions_admin_action_active_uidx
  ON admin_permissions (admin_id, menu_tab_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_admin_id_idx
  ON admin_permissions (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_menu_tab_action_id_idx
  ON admin_permissions (menu_tab_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permissions_set_updated_at ON admin_permissions;
CREATE TRIGGER admin_permissions_set_updated_at
  BEFORE UPDATE ON admin_permissions
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
