-- Bann Laundry schema
-- Soft delete: deleted_at IS NULL = แถวยังใช้
-- Query ปกติทุกตาราง: WHERE deleted_at IS NULL
-- Unique ของเบอร์ / อีเมล / ticket / code ใช้ partial index

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
  'อัปเดต updated_at อัตโนมัติทุกครั้งที่ UPDATE';

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone       VARCHAR(32)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  note        TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  users IS 'ลูกค้า';
COMMENT ON COLUMN users.id IS 'PK';
COMMENT ON COLUMN users.phone IS 'เบอร์โทร — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN users.name IS 'ชื่อลูกค้า';
COMMENT ON COLUMN users.note IS 'หมายเหตุ';
COMMENT ON COLUMN users.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN users.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN users.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS users_phone_active_uidx
  ON users (phone)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admins
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          VARCHAR(255) NOT NULL,
  display_name   VARCHAR(255) NOT NULL,
  role           VARCHAR(32)  NOT NULL DEFAULT 'staff'
                   CHECK (role IN ('owner', 'admin', 'staff')),
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admins IS 'พนักงาน / ผู้ดูแลระบบ (ข้อมูลโปรไฟล์)';
COMMENT ON COLUMN admins.id IS 'PK';
COMMENT ON COLUMN admins.email IS 'อีเมล — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN admins.display_name IS 'ชื่อที่แสดง';
COMMENT ON COLUMN admins.role IS 'owner | admin | staff';
COMMENT ON COLUMN admins.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admins.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admins.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admins_email_active_uidx
  ON admins (email)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admins_set_updated_at ON admins;
CREATE TRIGGER admins_set_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_auth
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_auth (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id       BIGINT       NOT NULL REFERENCES admins (id),
  password_hash  TEXT         NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admin_auth IS 'ข้อมูล auth ของ admin เช่น password hash';
COMMENT ON COLUMN admin_auth.id IS 'PK';
COMMENT ON COLUMN admin_auth.admin_id IS 'FK → admins.id (1 admin ต่อ 1 auth ที่ active)';
COMMENT ON COLUMN admin_auth.password_hash IS 'รหัสผ่านที่ hash แล้ว';
COMMENT ON COLUMN admin_auth.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_auth.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_auth.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_auth_admin_id_active_uidx
  ON admin_auth (admin_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_auth_set_updated_at ON admin_auth;
CREATE TRIGGER admin_auth_set_updated_at
  BEFORE UPDATE ON admin_auth
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- service_type
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS service_type (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(64)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  service_type IS 'ประเภทบริการ เช่น ซัก อบ พับ';
COMMENT ON COLUMN service_type.id IS 'PK';
COMMENT ON COLUMN service_type.code IS 'รหัสบริการ — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN service_type.name IS 'ชื่อบริการ';
COMMENT ON COLUMN service_type.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN service_type.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN service_type.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS service_type_code_active_uidx
  ON service_type (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS service_type_set_updated_at ON service_type;
CREATE TRIGGER service_type_set_updated_at
  BEFORE UPDATE ON service_type
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO service_type (code, name)
SELECT seed.code, seed.name
FROM (
  VALUES
    ('wash', 'ซัก'),
    ('dry', 'อบ'),
    ('iron', 'รีด')
) AS seed(code, name)
WHERE NOT EXISTS (
  SELECT 1
  FROM service_type st
  WHERE st.code = seed.code
    AND st.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- list_type
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS list_type (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(64)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  size        VARCHAR(64)  NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  list_type IS 'ชนิดรายการผ้า คู่ name + size เช่น เสื้อ/ปกติ, เสื้อ/ใหญ่';
COMMENT ON COLUMN list_type.id IS 'PK';
COMMENT ON COLUMN list_type.code IS 'รหัสสำหรับ logic — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN list_type.name IS 'ชนิดผ้า เช่น เสื้อ กางเกง';
COMMENT ON COLUMN list_type.size IS 'ขนาด เช่น ปกติ ใหญ่';
COMMENT ON COLUMN list_type.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN list_type.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN list_type.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS list_type_code_active_uidx
  ON list_type (code)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS list_type_name_size_active_uidx
  ON list_type (name, size)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS list_type_set_updated_at ON list_type;
CREATE TRIGGER list_type_set_updated_at
  BEFORE UPDATE ON list_type
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- list_price
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS list_price (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_type_id  BIGINT         NOT NULL REFERENCES service_type (id),
  list_type_id     BIGINT         NOT NULL REFERENCES list_type (id),
  unit_price       NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ
);

COMMENT ON TABLE  list_price IS 'ราคาต่อหน่วย ตามบริการ × ชนิดผ้า';
COMMENT ON COLUMN list_price.id IS 'PK';
COMMENT ON COLUMN list_price.service_type_id IS 'FK → service_type.id';
COMMENT ON COLUMN list_price.list_type_id IS 'FK → list_type.id';
COMMENT ON COLUMN list_price.unit_price IS 'ราคาต่อหน่วย';
COMMENT ON COLUMN list_price.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN list_price.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN list_price.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS list_price_service_list_active_uidx
  ON list_price (service_type_id, list_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS list_price_service_type_id_idx
  ON list_price (service_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS list_price_list_type_id_idx
  ON list_price (list_type_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS list_price_set_updated_at ON list_price;
CREATE TRIGGER list_price_set_updated_at
  BEFORE UPDATE ON list_price
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_no   VARCHAR(64)    NOT NULL,
  user_id     BIGINT         NOT NULL REFERENCES users (id),
  admin_id    BIGINT         REFERENCES admins (id),
  status      VARCHAR(32)    NOT NULL DEFAULT 'received'
                CHECK (status IN (
                  'received',
                  'processing',
                  'ready',
                  'completed',
                  'cancelled'
                )),
  subtotal    NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  discount    NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total       NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  note        TEXT,
  created_at  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ,
  CHECK (total = subtotal - discount)
);

COMMENT ON TABLE  orders IS 'ออเดอร์ซักรีด';
COMMENT ON COLUMN orders.id IS 'PK';
COMMENT ON COLUMN orders.ticket_no IS 'เลขใบรับผ้า — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN orders.user_id IS 'FK → users.id ลูกค้า';
COMMENT ON COLUMN orders.admin_id IS 'FK → admins.id พนักงานที่รับออเดอร์';
COMMENT ON COLUMN orders.status IS 'received | processing | ready | completed | cancelled';
COMMENT ON COLUMN orders.subtotal IS 'ยอดก่อนส่วนลด';
COMMENT ON COLUMN orders.discount IS 'ส่วนลด';
COMMENT ON COLUMN orders.total IS 'ยอดสุทธิ = subtotal - discount';
COMMENT ON COLUMN orders.note IS 'หมายเหตุออเดอร์';
COMMENT ON COLUMN orders.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN orders.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN orders.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS orders_ticket_no_active_uidx
  ON orders (ticket_no)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_user_id_idx
  ON orders (user_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_admin_id_idx
  ON orders (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS orders_status_idx
  ON orders (status)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS orders_set_updated_at ON orders;
CREATE TRIGGER orders_set_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         BIGINT         NOT NULL REFERENCES orders (id),
  service_type_id  BIGINT         NOT NULL REFERENCES service_type (id),
  list_type_id     BIGINT         NOT NULL REFERENCES list_type (id),
  list_price_id    BIGINT         REFERENCES list_price (id),
  qty              INTEGER        NOT NULL CHECK (qty > 0),
  unit_price       NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
  line_total       NUMERIC(12, 2) NOT NULL CHECK (line_total >= 0),
  note             TEXT,
  created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ,
  CHECK (line_total = qty * unit_price)
);

COMMENT ON TABLE  order_items IS 'รายการในออเดอร์';
COMMENT ON COLUMN order_items.id IS 'PK';
COMMENT ON COLUMN order_items.order_id IS 'FK → orders.id';
COMMENT ON COLUMN order_items.service_type_id IS 'FK → service_type.id snapshot ประเภทบริการ';
COMMENT ON COLUMN order_items.list_type_id IS 'FK → list_type.id snapshot ชนิดผ้า';
COMMENT ON COLUMN order_items.list_price_id IS 'FK → list_price.id ราคาที่อ้างอิงตอนสร้าง (nullable ถ้าราคาถูกลบ)';
COMMENT ON COLUMN order_items.qty IS 'จำนวน';
COMMENT ON COLUMN order_items.unit_price IS 'ราคาต่อหน่วย ณ ตอนสร้างรายการ';
COMMENT ON COLUMN order_items.line_total IS 'qty * unit_price';
COMMENT ON COLUMN order_items.note IS 'หมายเหตุรายการ';
COMMENT ON COLUMN order_items.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN order_items.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN order_items.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS order_items_order_id_idx
  ON order_items (order_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS order_items_service_type_id_idx
  ON order_items (service_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS order_items_list_type_id_idx
  ON order_items (list_type_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS order_items_set_updated_at ON order_items;
CREATE TRIGGER order_items_set_updated_at
  BEFORE UPDATE ON order_items
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- order_log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     BIGINT      NOT NULL REFERENCES orders (id),
  admin_id     BIGINT      REFERENCES admins (id),
  from_status  VARCHAR(32),
  to_status    VARCHAR(32),
  action       VARCHAR(64) NOT NULL,
  message      TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  order_log IS 'ประวัติออเดอร์ โดยปกติ insert อย่างเดียว';
COMMENT ON COLUMN order_log.id IS 'PK';
COMMENT ON COLUMN order_log.order_id IS 'FK → orders.id';
COMMENT ON COLUMN order_log.admin_id IS 'FK → admins.id ผู้ทำรายการ';
COMMENT ON COLUMN order_log.from_status IS 'สถานะเดิม (NULL ได้ เช่นตอนสร้างออเดอร์)';
COMMENT ON COLUMN order_log.to_status IS 'สถานะใหม่';
COMMENT ON COLUMN order_log.action IS 'ชนิดเหตุการณ์ เช่น create, status_change, note';
COMMENT ON COLUMN order_log.message IS 'ข้อความเพิ่มเติม';
COMMENT ON COLUMN order_log.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN order_log.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN order_log.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS order_log_order_id_idx
  ON order_log (order_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS order_log_admin_id_idx
  ON order_log (admin_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS order_log_set_updated_at ON order_log;
CREATE TRIGGER order_log_set_updated_at
  BEFORE UPDATE ON order_log
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
